package gui;

// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/logic/Lexer.flex

import compilerTools.Token;


@SuppressWarnings("fallthrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\126\u0100\1\u2600\1\u0100\1\u2700"+
    "\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\53\u0100\1\u2d00\10\u2e00"+
    "\31\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200\1\u3300"+
    "\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u0100\1\u3a00"+
    "\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100\1\u4200"+
    "\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800\1\u4900\1\u4a00"+
    "\1\u4b00\1\u4c00\1\u4d00\1\u1f00\1\u4e00\1\u4f00\1\u5000\1\u5100"+
    "\3\u0100\1\u5200\1\u5300\1\u5400\11\u1f00\1\u5500\4\u0100\1\u5600"+
    "\17\u1f00\2\u0100\1\u5700\41\u1f00\2\u0100\1\u5800\1\u5900\2\u1f00"+
    "\1\u5a00\1\u5b00\27\u0100\1\u5c00\4\u0100\1\u5d00\1\u5e00\41\u1f00"+
    "\1\u5f00\1\u0100\1\u6000\1\u6100\11\u1f00\1\u6200\22\u1f00\1\u6300"+
    "\1\u1f00\1\u6400\1\u6500\1\u1f00\1\u6600\1\u6700\1\u6800\1\u6900"+
    "\2\u1f00\1\u6a00\4\u1f00\1\u6b00\1\u6c00\1\u6d00\1\u6e00\4\u1f00"+
    "\1\u6f00\1\u7000\1\u7100\2\u1f00\1\u7200\1\u1f00\1\u7300\14\u1f00"+
    "\1\u7400\4\u1f00\246\u0100\1\u7500\20\u0100\1\u7600\1\u7700\25\u0100"+
    "\1\u7800\34\u0100\1\u7900\14\u1f00\2\u0100\1\u7a00\5\u1f00\23\u0100"+
    "\1\u7b00\u0aec\u1f00\1\u7c00\1\u7d00\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\16\0\4\5"+
    "\1\1\1\6\1\7\1\10\1\11\1\12\1\5\1\13"+
    "\1\14\1\15\1\16\1\12\1\17\1\12\1\20\1\21"+
    "\1\22\11\23\2\24\1\25\1\26\1\25\2\5\5\27"+
    "\1\30\7\27\1\31\5\27\1\32\6\27\1\24\1\5"+
    "\1\24\1\5\1\27\1\5\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\27\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\27\1\52\1\53\1\54"+
    "\1\55\1\27\1\56\1\57\1\60\1\27\1\61\1\5"+
    "\1\62\1\5\6\0\1\63\32\0\2\5\4\64\4\5"+
    "\1\64\2\5\1\0\7\5\1\64\4\5\1\64\5\5"+
    "\1\64\1\27\7\64\1\27\3\64\1\27\3\64\1\27"+
    "\1\64\1\27\3\64\1\5\2\64\1\27\1\64\1\27"+
    "\4\64\1\27\7\64\1\27\3\64\1\27\3\64\1\27"+
    "\1\64\1\27\3\64\1\5\2\64\1\27\1\64\1\27"+
    "\u01c5\64\4\5\14\64\16\5\5\64\7\5\1\64\1\5"+
    "\1\64\21\5\160\0\5\64\1\5\2\64\2\5\4\64"+
    "\1\5\1\64\6\5\1\64\1\5\3\64\1\5\1\64"+
    "\1\5\24\64\1\5\123\64\1\5\213\64\1\5\5\0"+
    "\2\5\246\64\1\5\46\64\2\5\1\64\6\5\51\64"+
    "\6\5\1\64\1\5\55\0\1\5\1\0\1\5\2\0"+
    "\1\5\2\0\1\5\1\0\10\5\33\64\4\5\4\64"+
    "\15\5\6\0\5\5\1\64\4\5\13\0\1\5\1\0"+
    "\3\5\53\64\37\0\4\5\2\64\1\0\143\64\1\5"+
    "\1\64\10\0\1\5\6\0\2\64\2\0\1\5\4\0"+
    "\2\64\12\0\3\64\2\5\1\64\17\5\1\0\1\64"+
    "\1\0\36\64\33\0\2\5\131\64\13\0\1\64\16\5"+
    "\12\0\41\64\11\0\2\64\4\5\1\64\2\5\1\0"+
    "\30\64\4\0\1\64\11\0\1\64\3\0\1\64\5\0"+
    "\22\5\31\64\3\0\4\5\13\64\5\5\30\64\1\5"+
    "\6\64\1\5\2\0\6\5\10\0\52\64\72\0\66\64"+
    "\3\0\1\64\22\0\1\64\7\0\12\64\2\0\2\5"+
    "\12\0\1\5\20\64\3\0\1\5\10\64\2\5\2\64"+
    "\2\5\26\64\1\5\7\64\1\5\1\64\3\5\4\64"+
    "\2\5\1\0\1\64\7\0\2\5\2\0\2\5\3\0"+
    "\1\64\10\5\1\0\4\5\2\64\1\5\3\64\2\0"+
    "\2\5\12\0\4\64\7\5\2\64\1\5\1\0\2\5"+
    "\3\0\1\5\6\64\4\5\2\64\2\5\26\64\1\5"+
    "\7\64\1\5\2\64\1\5\2\64\1\5\2\64\2\5"+
    "\1\0\1\5\5\0\4\5\2\0\2\5\3\0\3\5"+
    "\1\0\7\5\4\64\1\5\1\64\7\5\14\0\3\64"+
    "\1\0\13\5\3\0\1\5\11\64\1\5\3\64\1\5"+
    "\26\64\1\5\7\64\1\5\2\64\1\5\5\64\2\5"+
    "\1\0\1\64\10\0\1\5\3\0\1\5\3\0\2\5"+
    "\1\64\17\5\2\64\2\0\2\5\12\0\1\5\1\64"+
    "\7\5\1\64\6\0\1\5\3\0\1\5\10\64\2\5"+
    "\2\64\2\5\26\64\1\5\7\64\1\5\2\64\1\5"+
    "\5\64\2\5\1\0\1\64\7\0\2\5\2\0\2\5"+
    "\3\0\7\5\3\0\4\5\2\64\1\5\3\64\2\0"+
    "\2\5\12\0\1\5\1\64\20\5\1\0\1\64\1\5"+
    "\6\64\3\5\3\64\1\5\4\64\3\5\2\64\1\5"+
    "\1\64\1\5\2\64\3\5\2\64\3\5\3\64\3\5"+
    "\14\64\4\5\5\0\3\5\3\0\1\5\4\0\2\5"+
    "\1\64\6\5\1\0\16\5\12\0\11\5\1\64\6\5"+
    "\5\0\10\64\1\5\3\64\1\5\27\64\1\5\20\64"+
    "\2\5\1\0\1\64\7\0\1\5\3\0\1\5\4\0"+
    "\7\5\2\0\1\5\3\64\2\5\1\64\2\5\2\64"+
    "\2\0\2\5\12\0\20\5\1\64\3\0\1\5\10\64"+
    "\1\5\3\64\1\5\27\64\1\5\12\64\1\5\5\64"+
    "\2\5\1\0\1\64\7\0\1\5\3\0\1\5\4\0"+
    "\7\5\2\0\6\5\2\64\1\5\2\64\2\0\2\5"+
    "\12\0\1\5\2\64\15\5\4\0\11\64\1\5\3\64"+
    "\1\5\51\64\2\0\1\64\7\0\1\5\3\0\1\5"+
    "\4\0\1\64\5\5\3\64\1\0\7\5\3\64\2\0"+
    "\2\5\12\0\12\5\6\64\1\5\3\0\1\5\22\64"+
    "\3\5\30\64\1\5\11\64\1\5\1\64\2\5\7\64"+
    "\3\5\1\0\4\5\6\0\1\5\1\0\1\5\10\0"+
    "\6\5\12\0\2\5\2\0\15\5\60\64\1\0\2\64"+
    "\7\0\4\5\10\64\10\0\1\5\12\0\47\5\2\64"+
    "\1\5\1\64\1\5\5\64\1\5\30\64\1\5\1\64"+
    "\1\5\12\64\1\0\2\64\11\0\1\64\2\5\5\64"+
    "\1\5\1\64\1\5\6\0\2\5\12\0\2\5\4\64"+
    "\40\5\1\64\27\5\2\0\6\5\12\0\13\5\1\0"+
    "\1\5\1\0\1\5\1\0\4\5\2\0\10\64\1\5"+
    "\44\64\4\5\24\0\1\5\2\0\5\64\13\0\1\5"+
    "\44\0\11\5\1\0\71\5\53\64\24\0\1\64\12\0"+
    "\6\5\6\64\4\0\4\64\3\0\1\64\3\0\2\64"+
    "\7\0\3\64\4\0\15\64\14\0\1\64\17\0\2\5"+
    "\46\64\1\5\1\64\5\5\1\64\2\5\53\64\1\5"+
    "\115\64\1\5\4\64\2\5\7\64\1\5\1\64\1\5"+
    "\4\64\2\5\51\64\1\5\4\64\2\5\41\64\1\5"+
    "\4\64\2\5\7\64\1\5\1\64\1\5\4\64\2\5"+
    "\17\64\1\5\71\64\1\5\4\64\2\5\103\64\2\5"+
    "\3\0\40\5\20\64\20\5\126\64\2\5\6\64\3\5"+
    "\u016c\64\2\5\21\64\1\5\32\64\5\5\113\64\3\5"+
    "\13\64\7\5\22\64\4\0\11\5\23\64\3\0\13\5"+
    "\22\64\2\0\14\5\15\64\1\5\3\64\1\5\2\0"+
    "\14\5\64\64\40\0\3\5\1\64\3\5\2\64\1\0"+
    "\2\5\12\0\41\5\17\0\6\5\131\64\7\5\5\64"+
    "\2\0\42\64\1\0\1\64\5\5\106\64\12\5\37\64"+
    "\1\5\14\0\4\5\14\0\12\5\12\0\36\64\2\5"+
    "\5\64\13\5\54\64\4\5\32\64\6\5\12\0\46\5"+
    "\27\64\5\0\4\5\65\64\12\0\1\5\35\0\2\5"+
    "\13\0\6\5\12\0\15\5\1\64\10\5\16\0\1\5"+
    "\20\0\61\5\5\0\57\64\21\0\10\64\3\5\12\0"+
    "\21\5\11\0\14\5\3\0\36\64\15\0\2\64\12\0"+
    "\54\64\16\0\14\5\44\64\24\0\10\5\12\0\3\5"+
    "\3\64\12\0\44\64\2\5\11\64\7\5\53\64\2\5"+
    "\3\64\20\5\3\0\1\5\25\0\4\64\1\0\6\64"+
    "\1\0\2\64\3\0\1\64\5\5\300\64\100\0\26\64"+
    "\2\5\6\64\2\5\46\64\2\5\6\64\2\5\10\64"+
    "\1\5\1\64\1\5\1\64\1\5\1\64\1\5\37\64"+
    "\2\5\65\64\1\5\7\64\1\5\1\64\3\5\3\64"+
    "\1\5\7\64\3\5\4\64\2\5\6\64\4\5\15\64"+
    "\5\5\3\64\1\5\7\64\16\5\5\0\30\5\2\3"+
    "\5\0\20\5\2\64\23\5\1\64\13\5\5\0\1\5"+
    "\12\0\1\5\1\64\15\5\1\64\20\5\15\64\3\5"+
    "\41\64\17\5\15\0\4\5\1\0\3\5\14\0\21\5"+
    "\1\64\4\5\1\64\2\5\12\64\1\5\1\64\3\5"+
    "\5\64\6\5\1\64\1\5\1\64\1\5\1\64\1\5"+
    "\4\64\1\5\13\64\2\5\4\64\5\5\5\64\4\5"+
    "\1\64\21\5\51\64\u0177\5\345\64\6\5\4\64\3\0"+
    "\2\64\14\5\46\64\1\5\1\64\5\5\1\64\2\5"+
    "\70\64\7\5\1\64\17\5\1\0\27\64\11\5\7\64"+
    "\1\5\7\64\1\5\7\64\1\5\7\64\1\5\7\64"+
    "\1\5\7\64\1\5\7\64\1\5\7\64\1\5\40\0"+
    "\57\5\1\64\325\5\3\64\31\5\11\64\6\0\1\5"+
    "\5\64\2\5\5\64\4\5\126\64\2\5\2\0\2\5"+
    "\3\64\1\5\132\64\1\5\4\64\5\5\53\64\1\5"+
    "\136\64\21\5\40\64\60\5\320\64\100\5\215\64\103\5"+
    "\56\64\2\5\15\64\3\5\20\64\12\0\2\64\24\5"+
    "\57\64\1\0\4\5\12\0\1\5\37\64\2\0\120\64"+
    "\2\0\45\5\11\64\2\5\147\64\2\5\100\64\5\5"+
    "\2\64\1\5\1\64\1\5\5\64\30\5\20\64\1\0"+
    "\3\64\1\0\4\64\1\0\27\64\5\0\4\5\1\0"+
    "\13\5\1\64\7\5\64\64\14\5\2\0\62\64\22\0"+
    "\12\5\12\0\6\5\22\0\6\64\3\5\1\64\1\5"+
    "\2\64\13\0\34\64\10\0\2\5\27\64\15\0\14\5"+
    "\35\64\3\5\4\0\57\64\16\0\16\5\1\64\12\0"+
    "\6\5\5\64\1\0\12\64\12\0\5\64\1\5\51\64"+
    "\16\0\11\5\3\64\1\0\10\64\2\0\2\5\12\0"+
    "\6\5\27\64\3\5\1\64\3\0\62\64\1\0\1\64"+
    "\3\0\2\64\2\0\5\64\2\0\1\64\1\0\1\64"+
    "\30\5\3\64\2\5\13\64\5\0\2\5\3\64\2\0"+
    "\12\5\6\64\2\5\6\64\2\5\6\64\11\5\7\64"+
    "\1\5\7\64\1\5\53\64\1\5\16\64\6\5\163\64"+
    "\10\0\1\5\2\0\2\5\12\0\6\5\244\64\14\5"+
    "\27\64\4\5\61\64\4\5\u0100\3\156\64\2\5\152\64"+
    "\46\5\7\64\14\5\5\64\5\5\1\64\1\0\12\64"+
    "\1\5\15\64\1\5\5\64\1\5\1\64\1\5\2\64"+
    "\1\5\2\64\1\5\154\64\41\5\153\64\22\5\100\64"+
    "\2\5\66\64\50\5\15\64\3\5\20\0\20\5\20\0"+
    "\3\5\2\64\30\5\3\64\31\5\1\64\6\5\5\64"+
    "\1\5\207\64\2\5\1\0\4\5\1\64\13\5\12\0"+
    "\7\5\32\64\4\5\1\64\1\5\32\64\13\5\131\64"+
    "\3\5\6\64\2\5\6\64\2\5\6\64\2\5\3\64"+
    "\3\5\2\64\3\5\2\64\22\5\3\0\4\5\14\64"+
    "\1\5\32\64\1\5\23\64\1\5\2\64\1\5\17\64"+
    "\2\5\16\64\42\5\173\64\105\5\65\64\210\5\1\0"+
    "\202\5\35\64\3\5\61\64\17\5\1\0\37\5\40\64"+
    "\15\5\36\64\5\5\46\64\5\0\5\5\36\64\2\5"+
    "\44\64\4\5\10\64\1\5\5\64\52\5\236\64\2\5"+
    "\12\0\6\5\44\64\4\5\44\64\4\5\50\64\10\5"+
    "\64\64\14\5\13\64\1\5\17\64\1\5\7\64\1\5"+
    "\2\64\1\5\13\64\1\5\17\64\1\5\7\64\1\5"+
    "\2\64\103\5\67\64\11\5\26\64\12\5\10\64\30\5"+
    "\6\64\1\5\52\64\1\5\11\64\105\5\6\64\2\5"+
    "\1\64\1\5\54\64\1\5\2\64\3\5\1\64\2\5"+
    "\27\64\12\5\27\64\11\5\37\64\101\5\23\64\1\5"+
    "\2\64\12\5\26\64\12\5\32\64\106\5\70\64\6\5"+
    "\2\64\100\5\1\64\3\0\1\5\2\0\5\5\4\0"+
    "\4\64\1\5\3\64\1\5\35\64\2\5\3\0\4\5"+
    "\1\0\40\5\35\64\3\5\35\64\43\5\10\64\1\5"+
    "\34\64\2\0\31\5\66\64\12\5\26\64\12\5\23\64"+
    "\15\5\22\64\156\5\111\64\67\5\63\64\15\5\63\64"+
    "\15\5\44\64\4\0\10\5\12\0\u0146\5\52\64\1\5"+
    "\2\0\3\5\2\64\116\5\35\64\12\5\1\64\10\5"+
    "\26\64\13\0\37\5\22\64\4\0\52\5\25\64\33\5"+
    "\27\64\11\5\3\0\65\64\17\0\37\5\13\0\2\64"+
    "\2\0\1\64\11\5\4\0\55\64\13\0\2\5\1\0"+
    "\4\5\1\0\12\5\1\0\2\5\31\64\7\5\12\0"+
    "\6\5\3\0\44\64\16\0\1\5\12\0\4\5\1\64"+
    "\2\0\1\64\10\5\43\64\1\0\2\5\1\64\11\5"+
    "\3\0\60\64\16\0\4\64\4\5\4\0\1\5\14\0"+
    "\1\64\1\5\1\64\43\5\22\64\1\5\31\64\14\0"+
    "\6\5\1\0\101\5\7\64\1\5\1\64\1\5\4\64"+
    "\1\5\17\64\1\5\12\64\7\5\57\64\14\0\5\5"+
    "\12\0\6\5\4\0\1\5\10\64\2\5\2\64\2\5"+
    "\26\64\1\5\7\64\1\5\2\64\1\5\5\64\1\5"+
    "\2\0\1\64\7\0\2\5\2\0\2\5\3\0\2\5"+
    "\1\64\6\5\1\0\5\5\5\64\2\0\2\5\7\0"+
    "\3\5\5\0\213\5\65\64\22\0\4\64\5\5\12\0"+
    "\4\5\1\0\3\64\36\5\60\64\24\0\2\64\1\5"+
    "\1\64\10\5\12\0\246\5\57\64\7\0\2\5\11\0"+
    "\27\5\4\64\2\0\42\5\60\64\21\0\3\5\1\64"+
    "\13\5\12\0\46\5\53\64\15\0\1\64\7\5\12\0"+
    "\66\5\33\64\2\5\17\0\4\5\12\0\6\5\7\64"+
    "\271\5\54\64\17\0\145\5\100\64\12\0\25\5\10\64"+
    "\2\5\1\64\2\5\10\64\1\5\2\64\1\5\30\64"+
    "\6\0\1\5\2\0\2\5\4\0\1\64\1\0\1\64"+
    "\2\0\14\5\12\0\106\5\10\64\2\5\47\64\7\0"+
    "\2\5\7\0\1\64\1\5\1\64\1\0\33\5\1\64"+
    "\12\0\50\64\7\0\1\64\4\0\10\5\1\0\10\5"+
    "\1\64\13\0\56\64\20\0\3\5\1\64\22\5\111\64"+
    "\7\5\11\64\1\5\45\64\10\0\1\5\10\0\1\64"+
    "\17\5\12\0\30\5\36\64\2\5\26\0\1\5\16\0"+
    "\111\5\7\64\1\5\2\64\1\5\46\64\6\0\3\5"+
    "\1\0\1\5\2\0\1\5\7\0\1\64\1\0\10\5"+
    "\12\0\6\5\6\64\1\5\2\64\1\5\40\64\5\0"+
    "\1\5\2\0\1\5\5\0\1\64\7\5\12\0\u0136\5"+
    "\23\64\4\0\271\5\1\64\54\5\4\64\37\5\232\64"+
    "\146\5\157\64\21\5\304\64\u014c\5\141\64\17\5\57\64"+
    "\1\5\11\0\307\5\107\64\271\5\71\64\7\5\37\64"+
    "\1\5\12\0\6\5\117\64\1\5\12\0\6\5\36\64"+
    "\2\5\5\0\13\5\60\64\7\0\11\5\4\64\14\5"+
    "\12\0\11\5\25\64\5\5\23\64\260\5\100\64\200\5"+
    "\113\64\4\5\1\0\1\64\67\0\7\5\4\0\15\64"+
    "\100\5\2\64\1\5\1\64\1\0\13\5\2\0\16\5"+
    "\370\64\10\5\326\64\52\5\11\64\u01e7\5\4\64\1\5"+
    "\7\64\1\5\2\64\1\5\43\64\55\5\3\64\21\5"+
    "\4\64\10\5\u018c\64\4\5\153\64\5\5\15\64\3\5"+
    "\11\64\7\5\12\64\3\5\2\0\1\5\4\0\134\5"+
    "\56\0\2\5\27\0\u011e\5\5\0\3\5\26\0\2\5"+
    "\7\0\36\5\4\0\224\5\3\0\273\5\125\64\1\5"+
    "\107\64\1\5\2\64\2\5\1\64\2\5\2\64\2\5"+
    "\4\64\1\5\14\64\1\5\1\64\1\5\7\64\1\5"+
    "\101\64\1\5\4\64\2\5\10\64\1\5\7\64\1\5"+
    "\34\64\1\5\4\64\1\5\5\64\1\5\1\64\3\5"+
    "\7\64\1\5\u0154\64\2\5\31\64\1\5\31\64\1\5"+
    "\37\64\1\5\31\64\1\5\37\64\1\5\31\64\1\5"+
    "\37\64\1\5\31\64\1\5\37\64\1\5\31\64\1\5"+
    "\10\64\2\5\151\0\4\5\62\0\10\5\1\0\16\5"+
    "\1\0\26\5\5\0\1\5\17\0\120\5\37\64\341\5"+
    "\7\0\1\5\21\0\2\5\7\0\1\5\2\0\1\5"+
    "\5\0\325\5\55\64\3\5\7\0\7\64\2\5\12\0"+
    "\4\5\1\64\u0141\5\36\64\1\0\21\5\54\64\16\0"+
    "\5\5\1\64\340\5\7\64\1\5\4\64\1\5\2\64"+
    "\1\5\17\64\1\5\305\64\13\5\7\0\51\5\104\64"+
    "\7\0\1\64\4\5\12\0\u0156\5\1\64\117\5\4\64"+
    "\1\5\33\64\1\5\2\64\1\5\1\64\2\5\1\64"+
    "\1\5\12\64\1\5\4\64\1\5\1\64\1\5\1\64"+
    "\6\5\1\64\4\5\1\64\1\5\1\64\1\5\1\64"+
    "\1\5\3\64\1\5\2\64\1\5\1\64\2\5\1\64"+
    "\1\5\1\64\1\5\1\64\1\5\1\64\1\5\1\64"+
    "\1\5\2\64\1\5\1\64\2\5\4\64\1\5\7\64"+
    "\1\5\4\64\1\5\4\64\1\5\1\64\1\5\12\64"+
    "\1\5\21\64\5\5\3\64\1\5\5\64\1\5\21\64"+
    "\u0134\5\12\0\6\5\340\64\40\5\71\64\7\5\336\64"+
    "\2\5\u0182\64\16\5\u0131\64\37\5\36\64\342\5\113\64"+
    "\266\5\1\0\36\5\140\0\200\5\360\0\20\5";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[32256];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\1\1\2\1\1\1\3\1\1"+
    "\1\4\1\5\1\3\1\6\1\3\2\7\1\10\1\11"+
    "\1\12\24\13\1\14\1\15\1\11\1\0\1\7\1\16"+
    "\1\12\3\0\4\13\1\17\11\13\1\17\3\13\1\20"+
    "\7\13\1\7\24\13\1\7\24\13";

  private static int [] zzUnpackAction() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\65\0\152\0\237\0\324\0\u0109\0\u013e"+
    "\0\u0173\0\u01a8\0\65\0\65\0\u01dd\0\65\0\u0212\0\u0247"+
    "\0\u027c\0\65\0\237\0\237\0\u02b1\0\u02e6\0\u031b\0\u0350"+
    "\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3\0\u04f8"+
    "\0\u052d\0\u0562\0\u0597\0\u05cc\0\u0601\0\u0636\0\u066b\0\u06a0"+
    "\0\65\0\65\0\65\0\324\0\65\0\u06d5\0\65\0\u01a8"+
    "\0\u070a\0\u0247\0\u073f\0\u0774\0\u07a9\0\u07de\0\u0813\0\u0848"+
    "\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986\0\u09bb\0\u09f0"+
    "\0\u02b1\0\u0a25\0\u0a5a\0\u0a8f\0\u02b1\0\u0ac4\0\u0af9\0\u0b2e"+
    "\0\u0b63\0\u0b98\0\u0bcd\0\u0c02\0\u070a\0\u0c37\0\u0c6c\0\u0ca1"+
    "\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\u0e49"+
    "\0\u0e7e\0\u0eb3\0\u0ee8\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1"+
    "\0\u1026\0\u02b1\0\u105b\0\u1090\0\u10c5\0\u10fa\0\u112f\0\u1164"+
    "\0\u1199\0\u11ce\0\u1203\0\u1238\0\u126d\0\u12a2\0\u12d7\0\u130c"+
    "\0\u1341\0\u1376\0\u13ab\0\u13e0\0\u1415\0\u144a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\2\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\2"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\25\1\40\1\25\1\41\1\25\1\42\1\43"+
    "\1\44\1\45\1\25\1\46\1\25\1\47\1\25\1\50"+
    "\1\51\1\52\1\0\1\2\67\0\1\3\110\0\1\53"+
    "\37\0\2\54\1\0\1\54\2\0\1\55\12\0\2\54"+
    "\3\0\32\54\4\0\2\7\1\3\1\7\1\4\60\7"+
    "\11\0\1\56\15\0\32\56\3\0\1\56\26\0\1\57"+
    "\37\0\2\60\1\0\1\60\6\0\1\55\6\0\2\60"+
    "\3\0\32\60\22\0\1\11\7\0\1\57\57\0\1\11"+
    "\4\0\1\57\56\0\1\61\1\0\2\62\61\0\1\61"+
    "\1\0\2\21\63\0\2\25\3\0\32\25\26\0\2\25"+
    "\3\0\4\25\1\63\25\25\26\0\2\25\3\0\21\25"+
    "\1\64\10\25\26\0\2\25\3\0\23\25\1\65\6\25"+
    "\26\0\2\25\3\0\20\25\1\66\3\25\1\67\5\25"+
    "\26\0\2\25\3\0\23\25\1\70\6\25\26\0\2\25"+
    "\3\0\16\25\1\44\2\25\1\71\10\25\26\0\2\25"+
    "\3\0\10\25\1\72\21\25\26\0\2\25\3\0\16\25"+
    "\1\73\11\25\1\74\1\25\26\0\2\25\3\0\14\25"+
    "\1\75\4\25\1\76\1\25\1\77\6\25\26\0\2\25"+
    "\3\0\16\25\1\100\13\25\26\0\2\25\3\0\11\25"+
    "\1\101\5\25\1\102\1\101\3\25\1\101\5\25\26\0"+
    "\2\25\3\0\4\25\1\103\25\25\26\0\2\25\3\0"+
    "\21\25\1\104\10\25\26\0\2\25\3\0\23\25\1\105"+
    "\6\25\26\0\2\25\3\0\4\25\1\106\25\25\26\0"+
    "\2\25\3\0\4\25\1\107\3\25\1\110\21\25\26\0"+
    "\2\25\3\0\23\25\1\111\6\25\26\0\2\25\3\0"+
    "\13\25\1\112\1\113\15\25\26\0\2\25\3\0\14\25"+
    "\1\114\15\25\4\0\1\56\10\0\1\56\10\0\2\56"+
    "\3\0\32\56\2\0\2\56\22\0\2\115\63\0\2\25"+
    "\3\0\16\25\1\116\13\25\26\0\2\25\3\0\20\25"+
    "\1\117\11\25\26\0\2\25\3\0\26\25\1\120\3\25"+
    "\26\0\2\25\3\0\7\25\1\105\22\25\26\0\2\25"+
    "\3\0\24\25\1\121\5\25\26\0\2\25\3\0\10\25"+
    "\1\122\21\25\26\0\2\25\3\0\20\25\1\123\11\25"+
    "\26\0\2\25\3\0\11\25\1\101\4\25\1\101\13\25"+
    "\26\0\2\25\3\0\14\25\1\124\15\25\26\0\2\25"+
    "\3\0\6\25\1\125\23\25\26\0\2\25\3\0\20\25"+
    "\1\126\11\25\26\0\2\25\3\0\23\25\1\101\6\25"+
    "\26\0\2\25\3\0\21\25\1\127\10\25\26\0\2\25"+
    "\3\0\21\25\1\130\10\25\26\0\2\25\3\0\22\25"+
    "\1\131\7\25\26\0\2\25\3\0\17\25\1\132\12\25"+
    "\26\0\2\25\3\0\20\25\1\133\4\25\1\105\4\25"+
    "\26\0\2\25\3\0\24\25\1\134\5\25\26\0\2\25"+
    "\3\0\14\25\1\135\15\25\26\0\2\25\3\0\25\25"+
    "\1\136\4\25\26\0\2\25\3\0\31\25\1\101\26\0"+
    "\2\25\3\0\14\25\1\137\15\25\26\0\2\25\3\0"+
    "\25\25\1\140\4\25\26\0\2\25\3\0\10\25\1\141"+
    "\21\25\26\0\2\25\3\0\24\25\1\120\5\25\26\0"+
    "\2\25\3\0\10\25\1\101\21\25\26\0\2\25\3\0"+
    "\10\25\1\142\21\25\26\0\2\25\3\0\10\25\1\143"+
    "\21\25\26\0\2\25\3\0\4\25\1\144\25\25\26\0"+
    "\2\25\3\0\25\25\1\145\4\25\26\0\2\25\3\0"+
    "\11\25\1\146\20\25\26\0\2\25\3\0\10\25\1\147"+
    "\21\25\26\0\2\25\3\0\4\25\1\150\25\25\26\0"+
    "\2\25\3\0\17\25\1\101\12\25\26\0\2\25\3\0"+
    "\5\25\1\151\24\25\26\0\2\25\3\0\21\25\1\143"+
    "\10\25\26\0\2\25\3\0\5\25\1\152\24\25\26\0"+
    "\2\25\3\0\16\25\1\153\13\25\26\0\2\25\3\0"+
    "\24\25\1\101\5\25\26\0\2\25\3\0\24\25\1\117"+
    "\5\25\26\0\2\25\3\0\26\25\1\154\3\25\26\0"+
    "\2\25\3\0\16\25\1\117\13\25\26\0\2\25\3\0"+
    "\13\25\1\101\16\25\26\0\2\25\3\0\16\25\1\155"+
    "\13\25\26\0\2\25\3\0\23\25\1\156\6\25\26\0"+
    "\2\25\3\0\15\25\1\101\14\25\26\0\2\25\3\0"+
    "\14\25\1\157\15\25\26\0\2\25\3\0\10\25\1\160"+
    "\21\25\26\0\2\25\3\0\22\25\1\156\7\25\26\0"+
    "\2\25\3\0\16\25\1\161\13\25\26\0\2\25\3\0"+
    "\4\25\1\162\25\25\26\0\2\25\3\0\7\25\1\163"+
    "\22\25\26\0\2\25\3\0\21\25\1\164\10\25\26\0"+
    "\2\25\3\0\23\25\1\165\6\25\26\0\2\25\3\0"+
    "\7\25\1\101\22\25\26\0\2\25\3\0\25\25\1\101"+
    "\4\25\26\0\2\25\3\0\20\25\1\166\11\25\26\0"+
    "\2\25\3\0\16\25\1\135\13\25\26\0\2\25\3\0"+
    "\16\25\1\111\13\25\26\0\2\25\3\0\16\25\1\101"+
    "\13\25\26\0\2\25\3\0\4\25\1\101\25\25\26\0"+
    "\2\25\3\0\6\25\1\151\23\25\26\0\2\25\3\0"+
    "\20\25\1\101\11\25\26\0\2\25\3\0\26\25\1\117"+
    "\3\25\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5247];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\7\1\2\11\1\1\1\11\3\1\1\11"+
    "\26\1\3\11\1\0\1\11\1\1\1\11\3\0\104\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(String lexeme, String lexicalComp, int line, int column) {
        return new Token(lexeme, lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "ERROR", yyline, yycolumn);
            }
          // fall through
          case 17: break;
          case 2:
            { /*Ignore*/
            }
          // fall through
          case 18: break;
          case 3:
            { return token(yytext(), "ARITMETICO", yyline, yycolumn);
            }
          // fall through
          case 19: break;
          case 4:
            { return token(yytext(), "PARENTESIS_A", yyline, yycolumn);
            }
          // fall through
          case 20: break;
          case 5:
            { return token(yytext(), "PARENTESIS_B", yyline, yycolumn);
            }
          // fall through
          case 21: break;
          case 6:
            { return token(yytext(), "COMA", yyline, yycolumn);
            }
          // fall through
          case 22: break;
          case 7:
            { return token(yytext(), "CONSTANTES", yyline, yycolumn);
            }
          // fall through
          case 23: break;
          case 8:
            { return token(yytext(), "OTROS", yyline, yycolumn);
            }
          // fall through
          case 24: break;
          case 9:
            { return token(yytext(), "COMPARACION", yyline, yycolumn);
            }
          // fall through
          case 25: break;
          case 10:
            { return token(yytext(), "ASIGNACION", yyline, yycolumn);
            }
          // fall through
          case 26: break;
          case 11:
            { return token(yytext(), "IDENTIFICADORES", yyline, yycolumn);
            }
          // fall through
          case 27: break;
          case 12:
            { return token(yytext(), "LLAVE_A", yyline, yycolumn);
            }
          // fall through
          case 28: break;
          case 13:
            { return token(yytext(), "LLAVE_B", yyline, yycolumn);
            }
          // fall through
          case 29: break;
          case 14:
            { return token(yytext(), "IDENTIFICADOR", yyline, yycolumn);
            }
          // fall through
          case 30: break;
          case 15:
            { return token(yytext(), "PALABRAS CLAVE", yyline, yycolumn);
            }
          // fall through
          case 31: break;
          case 16:
            { return token(yytext(), "LOGICOS", yyline, yycolumn);
            }
          // fall through
          case 32: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
